#!/bin/bash
compass compile --sass-dir src/style/ --css-dir ./
$(npm bin)/coffee --compile --bare --output build src
$(npm bin)/browserify build/index.js -o dvl.js
$(npm bin)/uglifyjs dvl.js > dvl.min.js
