// Generated by CoffeeScript 1.6.2
var dvl;

dvl = require('./build/core');

dvl.data = require('./build/data');

dvl.async = require('./build/async');

dvl.bind = require('./build/bind').bind;

dvl.bindSingle = require('./build/bind').bindSingle;

dvl.html = require('./build/html');

dvl.svg = require('./build/svg');

dvl.snap = require('./build/snap');

dvl.util = require('./build/util');

module.exports = dvl;
