#!/bin/bash
compass watch --sass-dir src/style/ --css-dir ./ &
coffee --compile --bare --watch --output build src
coffee --compile --bare --watch --output index.js index.coffee
browserify index.js -o dvl.js
